const BASE=location.pathname.replace(/\/$/,'');
const route=path=>BASE+path;
const $=id=>document.getElementById(id);
let current=null,selected=null,tab='fields',timer=null;
const modeNames={auto:'智能选择',flash:'原生文字',basic:'本地OCR',standard:'高质量模型',advanced:'加强处理'};
const statusNames={queued:'排队中',running:'正在解析',done:'提取完成 · 请复核',failed:'未完成'};
const names={revenue:'营业收入',revenue_total:'营业总收入',assets_total:'总资产',equity_parent:'归母净资产',net_profit_parent:'归母净利润',net_profit_parent_adjusted:'扣非归母净利润',operating_cash_flow:'经营现金流净额',eps_basic:'基本每股收益',eps_diluted:'稀释每股收益',roe_weighted:'加权平均净资产收益率',award_amount:'中标金额',shareholder:'股东',pledged_shares:'本次质押数量',holder_ratio:'占所持股份比例',capital_ratio:'占总股本比例',pledge_start:'质押开始',pledge_end:'质押到期',pledgee:'质权人',purpose:'质押用途',before_shares:'变动前股数',after_shares:'变动后股数',before_ratio:'变动前比例',after_ratio:'变动后比例'};
const reasons={missing:'缺失',invalid:'数字格式异常',unit_unknown:'单位不明',period_unknown:'报告期不明',period_requires_document_context:'需确认具体报告期',reconstructed_split_label:'合并过拆行名称',conflicting_values_or_scope:'数值或口径冲突',percentage_out_of_range:'比例超出范围',confirm_tax_and_contract_scope:'确认含税及合同范围',verify_recognized_value_against_original:'核对识别结果'};
function el(tag,text,cls){const n=document.createElement(tag);if(text!==undefined)n.textContent=String(text);if(cls)n.className=cls;return n;}
async function api(url,opts={}){const r=await fetch(route(url),{...opts,headers:{'X-FinAI-Local':'1',...(opts.headers||{})}});const data=await r.json();if(!r.ok)throw new Error(data.detail||'请求失败');return data;}
async function list(){const rows=await api('/api/jobs');$('jobs').replaceChildren();for(const j of rows){const b=el('button',undefined,'job'+(j.id===selected?' selected':''));b.append(el('span',j.filename),el('small',statusNames[j.status]||j.status));b.onclick=()=>load(j.id);$('jobs').append(b);}}
async function load(id){selected=id;current=await api('/api/jobs/'+id);$('result-title').textContent=current.filename;$('result-status').textContent=(statusNames[current.status]||current.status)+' · '+(modeNames[current.tier]||current.tier)+' · '+(current.pages?'页码 '+current.pages:'全部页面');$('downloads').replaceChildren();$('summary').replaceChildren();$('tabs').hidden=current.status!=='done';if(current.status==='done'){for(const [name,label] of [['financial.json','结构化 JSON'],['fields.csv','字段 CSV'],['mineru_original.md','原始 Markdown'],['trace.json','运行记录']]){const a=el('a',label);a.href=route('/api/jobs/'+id+'/download/'+name);$('downloads').append(a);}const r=current.result;const chips=el('div',undefined,'chips');for(const text of [`${r.fields.length} 个财务字段`,`${r.events.length} 项公告记录`,`${r.tables.length} 张表格`])chips.append(el('span',text,'chip'));$('summary').append(chips);if(r.assistant){const a=r.assistant;const advice=el('div',undefined,'notice');advice.append(el('strong','本地处理建议'),el('p',a.plan.reason),el('p','识别类型：'+a.profiles.map(x=>x.label).join('、')+'；'+a.fields_with_flags+'个候选字段有复核提示。'));for(const tip of a.next_steps)advice.append(el('p',tip));$('summary').append(advice);}for(const w of r.warnings)$('summary').append(el('p',w,'notice'));render();}else{$('content').replaceChildren(el('p',current.error||'材料保存在本地，解析完成后将在此展示。',current.status==='failed'?'error':''));}await list();clearTimeout(timer);if(['queued','running'].includes(current.status))timer=setTimeout(()=>load(id).catch(showError),2500);}
function showError(e){$('message').textContent=e.message;$('message').className='error';}
function allFields(){const r=current.result;return [...r.fields.map((f,i)=>({id:'f'+i,...f})),...r.events.flatMap((e,i)=>Object.entries(e.fields).map(([key,f])=>({id:`e${i}:${key}`,name:key,event:e.type,shareholder:e.shareholder||e.fields.shareholder?.value,...f})))];}
function render(){const content=$('content');content.replaceChildren();for(const b of $('tabs').querySelectorAll('button'))b.classList.toggle('active',b.dataset.tab===tab);if(tab==='fields'){const scroll=el('div',undefined,'scroll'),table=el('table'),head=el('tr');for(const x of ['字段 / 记录','原值 → 标准值','单位 / 报告期','来源证据','复核'])head.append(el('th',x));table.append(head);for(const f of allFields()){const tr=el('tr');const title=el('td',names[f.name]||f.label||f.name);if(f.shareholder)title.append(el('small',f.shareholder));tr.append(title);const rev=(current.reviews||[]).filter(x=>x.field_id===f.id).at(-1);const val=rev?.action==='corrected'?rev.corrected_value:f.value;tr.append(el('td',f.raw+' → '+(val??'缺失'),'value'));const meta=el('td',(rev?.corrected_unit||f.unit||'未明确')+' / '+(rev?.corrected_period||f.period||'未明确'));if(f.currency)meta.append(el('small',f.currency));tr.append(meta);const ev=f.evidence||{},source=el('td'),a=el('a','第 '+ev.page+' 页','source');a.href=route('/api/jobs/'+current.id+'/source#page='+ev.page);a.target='_blank';a.rel='noopener';source.append(a,el('small',ev.table_id?`${ev.table_id} · 行${ev.row} 列${ev.column}`:'原文段落'),el('small',ev.quote));tr.append(source);const actions=el('td',undefined,'field-actions');actions.append(el('span',rev?.action==='confirmed'?'人工已确认':rev?.action==='corrected'?'人工已修正':(f.review_reasons||[]).map(x=>reasons[x]||x).join('；')||'待人工确认',rev?.action==='confirmed'?'confirmed':'review'));const ok=el('button','确认');ok.onclick=()=>saveReview(f,'confirmed');const edit=el('button','修正');edit.onclick=()=>saveReview(f,'corrected');actions.append(el('br'),ok,document.createTextNode(' '),edit);tr.append(actions);table.append(tr);}scroll.append(table);content.append(scroll);if(!allFields().length)content.append(el('p','尚无支持的字段，请检查原始表格和全文。','notice'));}else if(tab==='tables'){for(const t of current.result.tables){const d=el('details'),s=el('summary',`第 ${t.page} 页 · ${t.id} · ${t.rows.length} 行`),scroll=el('div',undefined,'scroll'),table=el('table');for(const row of t.rows){const tr=el('tr');for(const c of row)tr.append(el('td',c));table.append(tr);}scroll.append(table);d.append(s,scroll);content.append(d);}}else if(tab==='text'){for(const b of current.result.blocks){const d=el('details');d.append(el('summary',`第 ${b.page} 页 · ${b.kind} · 块 ${b.block}`),el('pre',b.text));content.append(d);}}else{content.append(el('p','原始提取结果保持不变；人工确认和修正另存为追加记录。导出的 financial.json / fields.csv 是原始候选，修正记录须另行下载。','notice'));const a=el('a','下载复核记录');a.href=route('/api/jobs/'+current.id+'/download/reviews.jsonl');content.append(a,el('pre',JSON.stringify(current.reviews||[],null,2)));}}
async function saveReview(f,action){try{let body={field_id:f.id,action,note:''};if(action==='corrected'){const value=prompt('按原文件修正标准值：',f.value??'');if(value===null)return;const unit=prompt('单位：',f.unit||'');if(unit===null)return;const period=prompt('报告期：',f.period||'');if(period===null)return;const note=prompt('请说明修正依据（如原文页码和正确口径）：');if(note===null)return;body={...body,corrected_value:value,corrected_unit:unit,corrected_period:period,note};}await api('/api/jobs/'+current.id+'/reviews',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});await load(current.id);}catch(e){showError(e);}}
$('upload').onsubmit=async e=>{e.preventDefault();const button=e.target.querySelector('button');button.disabled=true;$('message').textContent='正在保存本地文件…';try{const data=new FormData(e.target);const[tier,ocr]=$('mode').value.split(':');data.set('tier',tier);data.set('ocr',ocr);const j=await api('/api/jobs',{method:'POST',body:data});$('message').textContent='任务已保存。可继续查看结果或提交其他文件。';await load(j.id);}catch(e){showError(e);}finally{button.disabled=false;}};
$('refresh').onclick=()=>list().catch(showError);for(const b of $('tabs').querySelectorAll('button'))b.onclick=()=>{tab=b.dataset.tab;render();};list().catch(showError);
